### ISSUE TITLE
Failing to set up senna with provided instructions

### ISSUE THREAD

**Issue by jonathanold** [nitingupta910/senna#1]
I always get different errors (on MacOS). I have added senna to the `$PATH` environment. When I type
`gcc -o senna -O3 -ffast-math *.c -DUSE_APPLE_BLAS -framework Accelerate`,
I get the error `zsh: no matches found: *.c`. 
Any help?

**Comment by nitingupta910** [comment]
Sorry, I don't a Mac system to try on. Could you try running with the compile command within the bash shell instead? Looks like `*.c` is not being expanded as a list of all `.c` files by zsh.
